### PR TITLE
adding live updates and match selection prompt

### PR DESCRIPTION
**Pull request by debopamsengupta**
I added an option for seeing live updates, after posting https://github.com/sarthology/criCLI/issues/5 :) 
- by default, once every 30 seconds, but customisable
- moved the `Crawler` object creation out of the `crawlerFunction` to avoid creating new instances for every new fetch for live updates

Went a little further, for #7 
- Started using the livematches API to get the list of live matches happening
- Added a prompt to pick which match to track (in case 2 matches happening at the same time) 

This is what it looks like now 
cli

### CODE REVIEW

**Comment by debopamsengupta** [comment]
@sarthology @sharmarajat01 would you like to merge this ? :D

**Comment by sarthology** [comment]
@debopamsengupta Just checked the code last night. Great work champ. 🎊

**Comment by debopamsengupta** [comment]
@sarthology Thanks for merging ! The latest version hasn't been published though :D

**Comment by sarthology** [comment]
Done 😅

**Pull request merged**
